# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80

# spring
spring:
  # profiles:
  #   active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/oss?characterEncoding=utf8
      username: root
      password: cx19970522
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jpa:
    show-sql: false

#spring.jpa.generate-ddl: true

logging:
  level: info
  level.cn.nobitastudio.oss: debug
  path: /web/logs/oss/
  file: biz.log

# oss config
oss.app.scanInterval: 5
oss.app.maxBindCount: 5
oss.app.autoLaunchScan: true
oss.app.browser.loginPage: /html/login.html
oss.app.healthArticle: 7           # 初始化时每种类型的健康资讯数量